import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./component/header";
import Footer from "./component/footer";
import SmoothScroll from "./component/smooth-scroll";
import "./globals.css";

const helveticaNeue = localFont({
  src: [
    {
      path: "../public/fonts/HelveticaNeue-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/HelveticaNeueRegular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/HelveticaNeue-Medium.woff",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-neue",
  display: "swap",
});

const helveticaNeueLight = localFont({
  src: "../public/fonts/HelveticaNeue-Light.woff",
  variable: "--font-helvetica-neue-light",
  display: "swap",
});

const helveticaNeueRegular = localFont({
  src: "../public/fonts/HelveticaNeueRegular.woff",
  variable: "--font-helvetica-neue-regular",
  display: "swap",
});

const helveticaNeueMedium = localFont({
  src: "../public/fonts/HelveticaNeue-Medium.woff",
  variable: "--font-helvetica-neue-medium",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaNeue.className} ${helveticaNeue.variable} ${helveticaNeueLight.variable} ${helveticaNeueRegular.variable} ${helveticaNeueMedium.variable} antialiased`}
      >
        <SmoothScroll />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
