import type { Metadata } from "next";
import { Adamina, Inter } from "next/font/google";
import Header from "./component/header";
import Footer from "./component/footer";
import SmoothScroll from "./component/smooth-scroll";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-inter",
  display: "swap",
});

const adamina = Adamina({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-adamina",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${adamina.variable} antialiased`}>
        <SmoothScroll />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
